
SET FOREIGN_KEY_CHECKS=0;

-- crm tables -----------------------------------------------------------------------------------------------

-- ----------------------------
-- Table structure for CRM_CUSTOMER
-- ----------------------------
DROP TABLE IF EXISTS CRM_CUSTOMER;
CREATE TABLE CRM_CUSTOMER (
  ID      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  NAME      VARCHAR(100) COMMENT '名称',
  SHORT_NAME      VARCHAR(100) COMMENT '简称',
  USCC      CHAR(18) COMMENT '统一社会信用代码',
  ORIGIN      INTEGER(9) COMMENT '信息来源',
  AREA      INTEGER(9) COMMENT '所属区域',
  PROVINCE      INTEGER(9) COMMENT '所在省',
  CITY      INTEGER(9) COMMENT '所在市',
  DISTRICT      INTEGER(9) COMMENT '所在县区',
  ADDRESS  VARCHAR(400) COMMENT '地址',
  LONGITUDE  VARCHAR(50) COMMENT '经度',
  LATITUDE  VARCHAR(50) COMMENT '纬度',
  TEL  VARCHAR(20) COMMENT '公司电话',
  FAX  VARCHAR(20) COMMENT '公司传真',
  WEBSITE  VARCHAR(100) COMMENT '公司网站',
  LEGAL_REPRESENTATIVE  VARCHAR(100) COMMENT '法定代表人',
  LR_NUMBER  VARCHAR(20) COMMENT '法人电话',
  ESTABLISHMENT_DATE DATE COMMENT '成立日期',
  REGISTERED_CAPITAL DECIMAL(15,2) COMMENT '注册资金(万元)',
  NATURE    INTEGER(9) COMMENT '企业性质',
  INDUSTRY    INTEGER(9) COMMENT '所属行业',
  LISTING_STATUS    INTEGER(9) COMMENT '上市情况',
  SUPERIOR    VARCHAR(100) COMMENT '上级单位',
  IS_GROUP    CHAR(1) COMMENT '是否集团企业',
  SIZE    INTEGER(9) COMMENT '公司规模',
  TOTAL_ASSETS    DECIMAL(15,2) COMMENT '总资产(万元)',
  ANNUAL_OUTPUT_VALUE    DECIMAL(15,2) COMMENT '年产值(万元)',
  ANNUAL_OUTPUT_SCALE    INTEGER(9) COMMENT '年产值规模',
  EMPLOYEE_SIZE    INTEGER(9) COMMENT '员工规模',
  MAIN_BUSINESS     VARCHAR(500) COMMENT '主营业务',
  OPERATE_STATUS    INTEGER(9) COMMENT '经营状况',
  MARKET_POSITION    INTEGER(9) COMMENT '市场地位',
  POTENTIAL    INTEGER(9) COMMENT '发展潜力',
  HAS_IT_DEPARTMENT    CHAR(1) COMMENT '是否有信息部门',
  IT_MANAGER    VARCHAR(50) COMMENT '信息部主管',
  IT_MANAGER_NUMBER    VARCHAR(50) COMMENT '信息部主管电话',
  IT_SITUATION    VARCHAR(500) COMMENT '信息化状况',
  MAIN_SOFTWARE_BRAND    VARCHAR(1000) COMMENT '主要软件品牌',
  MAIN_SOFTWARE_LINE    VARCHAR(1000) COMMENT '主要软件产品线',
  ORIGIN_TRACKER VARCHAR(200) COMMENT '线索跟踪人',
  SALESMAN    VARCHAR(64) COMMENT '销售对应人',
  OLD_SALESMAN    VARCHAR(64) COMMENT '原销售对应人',
  SERVICEMAN    VARCHAR(64) COMMENT '服务对应人',
  CREATE_TIME    DATETIME COMMENT '创建时间',
  REMARK  VARCHAR(2000) COMMENT '描述',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户信息表';

-- ----------------------------
-- Table structure for CRM_CONTACT
-- ----------------------------
DROP TABLE IF EXISTS CRM_CONTACT;
CREATE TABLE CRM_CONTACT (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  CUSTOMER_ID             CHAR(36) COMMENT '客户ID',
  NAME    VARCHAR(200) NOT NULL COMMENT '姓名',
  GENDER INTEGER(9) NOT NULL COMMENT '性别',
  BIRTHDATE VARCHAR(20) COMMENT '生日',
  DEPARTMENT INTEGER(9) COMMENT '部门',
  POST INTEGER(9) COMMENT '职务',
  OFFICE_NUMBER  VARCHAR(20) COMMENT '办公电话',
  MOBILE_NUMBER  VARCHAR(20) COMMENT '手机号',
  WEIXIN  VARCHAR(20) COMMENT '微信号',
  EMAIL  VARCHAR(100) COMMENT '邮箱',
  QQ  VARCHAR(20) COMMENT 'QQ号码',
  CHARACTER_TRAIT VARCHAR(500) COMMENT '性格特点',
  FAMILY VARCHAR(500) COMMENT '家庭情况',
  PROFESSION VARCHAR(500) COMMENT '所学专业',
  BACKGROUND VARCHAR(500) COMMENT '背景',
  FACTIONS VARCHAR(500) COMMENT '公司内派系',
  TYPE  VARCHAR(20) COMMENT '联系人分类',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='联系人信息表';


-- ----------------------------
-- Table structure for CRM_INFORMATIONIZATION
-- ----------------------------
DROP TABLE IF EXISTS CRM_INFORMATIONIZATION;
CREATE TABLE CRM_INFORMATIONIZATION (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  CUSTOMER_ID             CHAR(36) COMMENT '客户ID',
  SUBJECT INTEGER(9) NOT NULL COMMENT '系统科目',
  PURCHASED    CHAR(1) COMMENT '是否已购买',
  BRAND    INTEGER(9) COMMENT '品牌',
  PRODUCT_LINE    INTEGER(9) COMMENT '产品线',
  SATISFACTION    INTEGER(9) COMMENT '满意度',
  STATE    INTEGER(9) COMMENT '运行状况',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='企业信息化明细表';


-- ----------------------------
-- Table structure for CU_CHANCE
-- ----------------------------
DROP TABLE IF EXISTS CRM_CHANCE;
CREATE TABLE CRM_CHANCE (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  NAME  VARCHAR(256) NOT NULL COMMENT '名称',
  CHANCE_PARTIN VARCHAR(256) NOT NULL COMMENT '机会参与人',
  COMPANY_ID  CHAR(36) COMMENT '所属公司ID',
  COMPANY_DEPT_ID  CHAR(36) COMMENT '所属部门ID',
  CUSTOMER_ID  CHAR(36) COMMENT '客户ID',
  SALESMAN_ID  CHAR(36) COMMENT '销售ID',
  PRE_SELLERS  VARCHAR(1000) COMMENT '售前支持ID',
  CHANCE_MONEY  INTEGER(11) COMMENT '销售金额',
  CHANCE_STEP  INTEGER(11) COMMENT '销售阶段',
  CHANCE_STEP_JSON  VARCHAR(2048) COMMENT '销售阶段JSON串',
  CHANCE_RESULT_DATE  CHAR(19) COMMENT '结单日期',
  CHANCE_DESC  VARCHAR(2048) COMMENT '机会描述',
  CHANCE_RIGHT  INT(6) COMMENT '查看权限',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商机信息表';

-- ----------------------------
-- Table structure for CU_CUSTOMER_EXT
-- ----------------------------
DROP TABLE IF EXISTS CU_ENTITY_EXT;
CREATE TABLE CU_ENTITY_EXT (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  ENTITY_ID             CHAR(36) COMMENT '对象ID',
  EXT_ID                    CHAR(36) NOT NULL COMMENT '附加信息主键',
  EXT_VALUE                 VARCHAR(200) COMMENT '附加信息值',
  SORT_NUMBER                  INT(9) COMMENT '显示顺序号',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户附加信息表';

-- ----------------------------
-- Table structure for CU_DAILY
-- ----------------------------
# DROP TABLE IF EXISTS CU_DAILY;
# CREATE TABLE CU_DAILY (
#   ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
#   DAILY_TITLE   VARCHAR(128) NOT NULL COMMENT '主题',
#   DAILY_RECEIVED   VARCHAR(64) NOT NULL COMMENT '主送人',
#   DAILY_CC   VARCHAR(2048) NOT NULL COMMENT '抄送人',
#   DAILY_PERSON   VARCHAR(64) NOT NULL COMMENT '创建人',
#   DAILY_CONTENT VARCHAR(100) COMMENT '内容',
#   DAILY_FILE_IDS  VARCHAR(2048) COMMENT '附件',
#   DAILY_IS_TIMING  INT(6) COMMENT '是否定时',
#   DAILY_TIMING  CHAR(19) COMMENT '定时时间',
#   DAILY_SEND_TIME  CHAR(19) COMMENT '发送时间',
#   DAILY_IS_MAIL  INT(6) COMMENT '是否邮件',
#   DAILY_IS_NOTICE  INT(6) COMMENT '是否通知',
#   DAILY_IS_READED  INT(6) COMMENT '是否已读',
#   DAILY_IS_COMMENT  VARCHAR(256) COMMENT '是否批注已读',
#   TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
#   DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
#   LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
#   LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='日报表';

-- ----------------------------
-- Table structure for CU_DOC
-- ----------------------------
# DROP TABLE IF EXISTS CU_DOC;
# CREATE TABLE CU_DOC (
#   ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
#   DOC_NAME               VARCHAR(128) NOT NULL COMMENT '名称',
#   FILE_ID                 VARCHAR(64) COMMENT '文件ID',
#   DOC_CORP                 VARCHAR(64) COMMENT '所属公司',
#   DOC_DEPT                 VARCHAR(64) COMMENT '所属部门',
#   DOC_CUSTOMER                 VARCHAR(64) COMMENT '所属客户',
#   DOC_PERSON                 VARCHAR(64) COMMENT '所属人员',
#   DOC_FREQUENCY                 INT(11) COMMENT '使用频率',
#   DOC_CREATE_DATE                 VARCHAR(64) COMMENT '创建时间',
#   DOC_UPDATE_DATE                 VARCHAR(64) COMMENT '修改时间',
#   TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
#   DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
#   LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
#   LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文档表';

-- ----------------------------
-- Table structure for CU_EXT
-- ----------------------------
DROP TABLE IF EXISTS CU_EXT;
CREATE TABLE CU_EXT (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  MODULE                    VARCHAR(200) COMMENT '模块名称',
  TABLE_NAME                    VARCHAR(200) COMMENT '附加主表名称',
  EXT_KEY               VARCHAR(200) COMMENT '附加信息KEY',
  EXT_NAME               VARCHAR(200) COMMENT '显示名称',
  EXT_TYPE               VARCHAR(200) COMMENT '类型',
  EXT_SHOW_TYPE               VARCHAR(200) COMMENT '显示类型',
  SORT_NUMBER             INTEGER(9) COMMENT '排序号',
  REMARK                  VARCHAR(1000) COMMENT '备注',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='附加信息表';

-- ----------------------------
-- Table structure for CU_SCHEDULE
-- ----------------------------
DROP TABLE IF EXISTS CU_SCHEDULE;
CREATE TABLE CU_SCHEDULE (
  ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  COMPANY_ID  VARCHAR(64) COMMENT '所属公司',
  COMPANY_DEPT_ID  VARCHAR(64) COMMENT '所属部门',
  SCHEDULE_TITLE  VARCHAR(128) COMMENT '标题',
  SCHEDULE_VISIT  INT(9) COMMENT '拜访类型',
  SCHEDULE_PARTIN  VARCHAR(256) COMMENT '参与人',
  CUSTOMER_ID CHAR(36) COMMENT '客户ID',
  CHANCE_ID  VARCHAR(64) COMMENT '关联商机',
  SCHEDULE_START  CHAR(19) COMMENT '开始时间',
  SCHEDULE_END  CHAR(19) COMMENT '结束时间',
  SCHEDULE_ADDRESS  VARCHAR(256) COMMENT '地点',
  SCHEDULE_LATITUDE  VARCHAR(256) COMMENT '纬度',
  SCHEDULE_LONGITUDE  VARCHAR(256) COMMENT '经度',
  SCHEDULE_CONTENT  VARCHAR(2048) COMMENT '内容',
  SCHEDULE_PHOTO  VARCHAR(2048) COMMENT '照片',
  SCHEDULE_CREATE_ID  VARCHAR(64) COMMENT '创建人',
  SCHEDULE_CREATE_TIME  CHAR(19) COMMENT '创建时间',
  TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
  DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
  LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
  LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='日程表';

-- ----------------------------
-- Table structure for CU_SIGN
-- ----------------------------
# DROP TABLE IF EXISTS CU_SIGN;
# CREATE TABLE CU_SIGN (
#   ID                      CHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
#   SIGN_CORP               VARCHAR(64)  COMMENT '公司',
#   SIGN_DEPT               VARCHAR(64) COMMENT '部门',
#   SIGN_USER               VARCHAR(64) COMMENT '人员',
#   SIGN_DATE                 CHAR(10) COMMENT '签到日期',
#   SIGN_IN_TIME                 CHAR(19) COMMENT '签到时间',
#   SIGN_IN_ADDRESS VARCHAR(256) COMMENT '签到位置',
#   SIGN_IN_LATITUDE VARCHAR(256) COMMENT '签到纬度',
#   SIGN_IN_LONGGITUDE VARCHAR(256) COMMENT '签到经度',
#   SIGN_OUT_TIME                 CHAR(19) COMMENT '签退时间',
#   SIGN_OUT_ADDRESS VARCHAR(256) COMMENT '签退位置',
#   SIGN_OUT_LATITUDE VARCHAR(256) COMMENT '签退纬度',
#   SIGN_OUT_LONGGITUDE VARCHAR(256) COMMENT '签退经度',
#   TENANT_ID               VARCHAR(36) NOT NULL COMMENT '租户ID',
#   DELETED                 CHAR(1) NOT NULL COMMENT '是否删除',
#   LAST_MODIFY_ACCOUNT_ID  VARCHAR(36) NOT NULL COMMENT '操作人',
#   LAST_MODIFY_TIME        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间'
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='签到表';