<link rel="stylesheet" href="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/style.css" type="text/css" media="screen">
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/jstools.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/raphael.js"></script>

<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/jquery/jquery.asyncqueue.js"></script>

<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/Color.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/Polyline.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/ActivityImpl.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/ActivitiRest.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/LineBreakMeasurer.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/ProcessDiagramGenerator.js"></script>
<script type="text/javascript" charset="utf-8" src="${pageContext.request.contextPath}/resources/script/act/diagram-viewer/js/ProcessDiagramCanvas.js"></script>
